// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectO.api.Data;

#nullable disable

namespace projectO.api.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20250726174116_seeddata1")]
    partial class seeddata1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("projectO.api.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "The job market is clutter right now i dont know why",
                            Title = "Infaltion"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
